<?php
/**
 * Example configuration file.
 *
 * Copy to `config.php` and customize for your installation.
 * IMPORTANT: `config.php` is intentionally excluded from Git (contains secrets).
 * 
 * After installation, this file will be auto-generated by the installer.
 * You can also manually configure it using this template.
 */

// Secure session configuration
if (session_status() === PHP_SESSION_NONE) {
    ini_set('session.cookie_httponly', 1);
    ini_set('session.cookie_secure', 1);
    ini_set('session.use_strict_mode', 1);
    ini_set('session.cookie_samesite', 'Lax');
    session_start();
}

// Environment detection
$isProduction = (strpos($_SERVER['HTTP_HOST'] ?? '', 'localhost') === false && 
                 strpos($_SERVER['HTTP_HOST'] ?? '', '127.0.0.1') === false &&
                 strpos($_SERVER['HTTP_HOST'] ?? '', '.local') === false &&
                 strpos($_SERVER['HTTP_HOST'] ?? '', '.test') === false);

// Database configuration (set by installer)
define('DB_HOST', 'localhost');
define('DB_NAME', 'business_cards');
define('DB_USER', 'root');
define('DB_PASS', '');
define('DB_PORT', '3306');
define('DB_TYPE', 'mysql'); // 'mysql' or 'pgsql'

// Base paths
define('BASE_DIR', __DIR__);
define('INCLUDES_DIR', BASE_DIR . '/includes');
define('DATA_DIR', BASE_DIR . '/data');
define('UPLOADS_DIR', BASE_DIR . '/uploads');
define('TEMPLATES_DIR', UPLOADS_DIR . '/templates');
define('CARDS_DIR', UPLOADS_DIR . '/cards');
define('EXCEL_DIR', UPLOADS_DIR . '/excel');
define('ASSETS_DIR', BASE_DIR . '/assets');

// Site settings
define('SITE_NAME', 'Cardify');
define('SITE_DESCRIPTION', 'Professional Business Card Generator');

// Timezone
date_default_timezone_set('Asia/Muscat');

// Error reporting (production-safe)
if ($isProduction) {
    // Production: Log errors but don't display them
    error_reporting(E_ALL);
    ini_set('display_errors', 0);
    ini_set('log_errors', 1);
    ini_set('error_log', BASE_DIR . '/logs/php-errors.log');
    
    // Create logs directory if it doesn't exist
    if (!is_dir(BASE_DIR . '/logs')) {
        mkdir(BASE_DIR . '/logs', 0755, true);
    }
} else {
    // Development: Show errors
    error_reporting(E_ALL);
    ini_set('display_errors', 1);
    ini_set('log_errors', 1);
}

// Billing/Payment Gateway Configuration
define('BILLING_GATEWAY', 'paymob'); // 'paymob', 'stripe', 'none'

// Paymob Configuration (Unified Checkout / Intention API)
// Get these from your Paymob dashboard: https://accept.paymob.com
if (!defined('PAYMOB_PUBLIC_KEY')) define('PAYMOB_PUBLIC_KEY', '');       // Public key for checkout iframe
if (!defined('PAYMOB_SECRET_KEY')) define('PAYMOB_SECRET_KEY', '');       // Secret key for API calls
if (!defined('PAYMOB_HMAC_SECRET')) define('PAYMOB_HMAC_SECRET', '');     // HMAC secret for callback verification
if (!defined('PAYMOB_INTEGRATION_IDS')) define('PAYMOB_INTEGRATION_IDS', '63364,65553,48519'); // Int'l 3DS, OmanNet 3DS, Apple Pay
if (!defined('PAYMOB_MOTO_INTEGRATION_ID')) define('PAYMOB_MOTO_INTEGRATION_ID', '63365');     // MOTO Int'l (card-on-file/subscriptions)
if (!defined('PAYMOB_MOTO_OMANNET_INTEGRATION_ID')) define('PAYMOB_MOTO_OMANNET_INTEGRATION_ID', '65554'); // MOTO OmanNet

// Legacy Amwal Pay Configuration (deprecated — kept for reference)
// if (!defined('AMWAL_MERCHANT_ID')) define('AMWAL_MERCHANT_ID', '');
// if (!defined('AMWAL_TERMINAL_ID')) define('AMWAL_TERMINAL_ID', '');
// if (!defined('AMWAL_SECURE_KEY')) define('AMWAL_SECURE_KEY', '');
// if (!defined('AMWAL_API_URL')) define('AMWAL_API_URL', 'https://backend.sa.amwal.tech');

// Stripe Configuration (alternative payment gateway)
if (!defined('STRIPE_SECRET_KEY')) define('STRIPE_SECRET_KEY', ''); // Stripe secret key
if (!defined('STRIPE_PUBLIC_KEY')) define('STRIPE_PUBLIC_KEY', ''); // Stripe public key

// Print Webhook Configuration
// Global secret for verifying print status webhooks (per-shop secrets take priority)
// Callers must send X-Webhook-Signature: sha256=<hmac_hex_of_body>
if (!defined('PRINT_WEBHOOK_SECRET')) define('PRINT_WEBHOOK_SECRET', ''); // Set a random secret string

// SEO & Analytics
define('GA_MEASUREMENT_ID', '');         // Google Analytics e.g. G-XXXXXXXXXX
define('GOOGLE_SITE_VERIFICATION', '');  // Google Search Console verification meta tag content

// Email/SMTP Configuration (required for password reset, notifications)
// Common providers:
// - Gmail: smtp.gmail.com, port 587, tls (requires App Password)
// - Outlook: smtp.office365.com, port 587, tls
// - Mailgun: smtp.mailgun.org, port 587, tls
// - SendGrid: smtp.sendgrid.net, port 587, tls
if (!defined('MAIL_HOST')) define('MAIL_HOST', ''); // SMTP server hostname
if (!defined('MAIL_PORT')) define('MAIL_PORT', 587); // SMTP port (587 for TLS, 465 for SSL)
if (!defined('MAIL_USERNAME')) define('MAIL_USERNAME', ''); // SMTP username (usually email)
if (!defined('MAIL_PASSWORD')) define('MAIL_PASSWORD', ''); // SMTP password or app password
if (!defined('MAIL_ENCRYPTION')) define('MAIL_ENCRYPTION', 'tls'); // 'tls', 'ssl', or '' for none
if (!defined('MAIL_FROM_EMAIL')) define('MAIL_FROM_EMAIL', ''); // From email (defaults to username)
if (!defined('MAIL_FROM_NAME')) define('MAIL_FROM_NAME', 'Cardify'); // From name

// Include required files
require_once INCLUDES_DIR . '/Database.php';
require_once INCLUDES_DIR . '/functions.php';
require_once INCLUDES_DIR . '/DatabaseAdapter.php';
require_once INCLUDES_DIR . '/AuditLog.php';

// Initialize database connection (if configured)
if (defined('DB_HOST') && !empty(DB_HOST) && !empty(DB_NAME)) {
    $db = Database::getInstance();
    if (!$db->isConnected()) {
        $db->connect(DB_HOST, DB_NAME, DB_USER, DB_PASS, DB_PORT, DB_TYPE);
    }
    // Initialize DatabaseAdapter
    DatabaseAdapter::init();
}

// Security headers (production)
if ($isProduction) {
    // Force HTTPS in production
    if (!isset($_SERVER['HTTPS']) && $_SERVER['HTTP_HOST'] !== 'localhost') {
        header('Location: https://' . $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI'], true, 301);
        exit;
    }
    
    // Security headers
    header('X-Content-Type-Options: nosniff');
    header('X-Frame-Options: SAMEORIGIN');
    header('X-XSS-Protection: 1; mode=block');
    header('Referrer-Policy: strict-origin-when-cross-origin');
    header('Permissions-Policy: camera=(), microphone=(), geolocation=()');

    // HSTS (HTTP Strict Transport Security) - only if HTTPS
    if (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on') {
        header('Strict-Transport-Security: max-age=31536000; includeSubDomains');
    }
}
