<?php
/**
 * Example configuration file.
 *
 * Copy to `config.php` and customize for your installation.
 * IMPORTANT: `config.php` is intentionally excluded from Git (contains secrets).
 * 
 * After installation, this file will be auto-generated by the installer.
 * You can also manually configure it using this template.
 */

// Start session, public SEO pages skip session unless tracking params are present
// (session_start() forces no-cache headers which hurts Google indexing).
$scriptName = basename($_SERVER['SCRIPT_NAME'] ?? '');
$requestUri = $_SERVER['REQUEST_URI'] ?? '';

// Authenticated/admin routes, never apply public-SEO caching to these,
// otherwise browsers cache redirects and users get redirect loops after role changes
$adminPathPrefixes = ['/admin/', '/admin', '/printshop/', '/printshop', '/api/'];
$isAdminPath = false;
foreach ($adminPathPrefixes as $prefix) {
    if (strpos($requestUri, $prefix) === 0) { $isAdminPath = true; break; }
}

$publicSeoPages = [
    'blog.php', 'about.php', 'faq.php', 'contact.php', 'terms.php',
    'privacy.php', 'delete-account.php', 'security.php', 'cookies.php', 'careers.php',
    'sitemap.php', 'index.php', 'intro.php', 'get-started.php',
    'restaurants.php', 'construction.php', 'healthcare.php',
    'real-estate.php', 'tourism.php',
    // Free client-side tools (SEO content pages)
    'vcard-qr-generator.php', 'email-signature-generator.php',
    'whatsapp-qr-generator.php', 'nfc-business-card-guide.php',
    // Press / backlink-magnet pages
    'oman-business-index.php',
    // Oman-specific solution pages (commercial-intent SEO)
    'solutions.php',
    'digital-business-cards-oman-sales-teams.php',
    'bilingual-arabic-english-business-cards.php',
    'qr-code-menu-muscat-restaurants.php',
    'business-cards-for-ramadan-networking.php',
    'nfc-business-cards-oman-executives.php',
    'digital-business-cards-oil-gas-oman.php',
    'business-cards-omani-law-firms.php',
    'digital-cards-oman-real-estate-agents.php',
    'business-cards-muscat-doctors-clinics.php',
    'business-cards-oman-construction-companies.php',
    'digital-business-cards-sohar-industrial-port.php',
    'salalah-tourism-business-cards.php',
    'business-cards-oman-bank-employees.php',
    'business-cards-for-oman-trade-fairs.php',
    'digital-business-cards-oman-hotels.php',
    'business-cards-oman-government-employees.php',
    'business-cards-oman-freelancers-consultants.php',
    'business-cards-oman-startups.php',
    'business-cards-oman-omanisation.php',
    'business-cards-duqm-free-zone.php',
];
$alwaysSkipSession = ['vcf.php', 'qr.php', 'feed.php'];

$hasTrackingParam = !empty($_GET['ref']) || !empty($_GET['utm_source'])
    || !empty($_GET['utm_medium']) || !empty($_GET['utm_campaign']);

$isPublicSeo = in_array($scriptName, $publicSeoPages) && !$isAdminPath;
$skipSession = in_array($scriptName, $alwaysSkipSession)
    || ($isPublicSeo && !$hasTrackingParam);

if ($isPublicSeo && $hasTrackingParam && session_status() === PHP_SESSION_NONE) {
    session_cache_limiter('public');
    session_cache_expire(60);
}

if (!$skipSession && session_status() === PHP_SESSION_NONE) {
    ini_set('session.cookie_httponly', 1);
    ini_set('session.cookie_secure', 1);
    ini_set('session.use_strict_mode', 1);
    ini_set('session.cookie_samesite', 'Lax');
    // Bump session lifetime to 4 hours (default 24min was too short for
    // casual visitors filling out the portal form: they'd open the page,
    // get distracted, come back, hit submit and get "Invalid request"
    // because gc_maxlifetime had wiped their CSRF token. 4h covers a
    // typical work-day pause without being so long it weakens auth.
    ini_set('session.gc_maxlifetime', 14400);   // 4 hours
    ini_set('session.cookie_lifetime', 14400);  // browser-side cookie too
    // Share session across {slug}.cardify.om subdomains so post-signup
    // redirect to tenant subdomain doesn't lose the login. Use a fresh
    // cookie name (CARDIFY_SID) instead of PHPSESSID so any stale
    // host-only PHPSESSID cookies left over from before the migration
    // don't shadow the new apex-scoped cookie (browsers send the more-
    // specific host-only cookie first, which would point at a deleted
    // session and silently log the user out on /admin/).
    $__sessHost = strtolower(preg_replace('/:\d+$/', '', $_SERVER['HTTP_HOST'] ?? ''));
    if ($__sessHost === 'cardify.om' || (strlen($__sessHost) > 11 && substr($__sessHost, -11) === '.cardify.om')) {
        ini_set('session.cookie_domain', '.cardify.om');
        ini_set('session.name', 'CARDIFY_SID');
    }
    session_start();
}

// Emit SEO-friendly cache headers on public pages that skipped session.
// Vary on Cookie so users with a cardify_lang preference don't get served
// a cached copy in the wrong language. When the visitor already has a
// language cookie, drop to no-cache so a stale Arabic copy clears
// immediately after they (or we) switch back to English.
if ($skipSession && $isPublicSeo && !headers_sent()) {
    $hasLangCookie = isset($_COOKIE['cardify_lang'])
        || isset($_COOKIE['cardify_lang_v2'])
        || isset($_COOKIE['cardify_lang_v3']);
    if ($hasLangCookie) {
        header('Cache-Control: private, no-cache, no-store, must-revalidate');
        header('Pragma: no-cache');
        header('Expires: 0');
    } else {
        header('Cache-Control: public, max-age=3600, s-maxage=3600');
    }
    header('Vary: Accept-Encoding, Cookie');
}

// Environment detection
$isProduction = (strpos($_SERVER['HTTP_HOST'] ?? '', 'localhost') === false && 
                 strpos($_SERVER['HTTP_HOST'] ?? '', '127.0.0.1') === false &&
                 strpos($_SERVER['HTTP_HOST'] ?? '', '.local') === false &&
                 strpos($_SERVER['HTTP_HOST'] ?? '', '.test') === false);

// Database configuration (set by installer)
define('DB_HOST', '127.0.0.1');
define('DB_NAME', 'business_cards');
define('DB_USER', 'root');
define('DB_PASS', '');
define('DB_PORT', '3306');
define('DB_TYPE', 'mysql'); // 'mysql' or 'pgsql'

// Base paths
define('BASE_DIR', __DIR__);
define('INCLUDES_DIR', BASE_DIR . '/includes');
define('DATA_DIR', BASE_DIR . '/data');
define('UPLOADS_DIR', BASE_DIR . '/uploads');
define('TEMPLATES_DIR', UPLOADS_DIR . '/templates');
define('CARDS_DIR', UPLOADS_DIR . '/cards');
define('EXCEL_DIR', UPLOADS_DIR . '/excel');
define('ASSETS_DIR', BASE_DIR . '/assets');

// Site settings
define('SITE_NAME', 'Cardify');
define('SITE_DESCRIPTION', 'Professional Business Card Generator');

// Timezone
date_default_timezone_set('Asia/Muscat');

// Error reporting (production-safe)
if ($isProduction) {
    // Production: Log errors but don't display them
    error_reporting(E_ALL);
    ini_set('display_errors', 0);
    ini_set('log_errors', 1);
    ini_set('error_log', BASE_DIR . '/logs/php-errors.log');
    
    // Create logs directory if it doesn't exist
    if (!is_dir(BASE_DIR . '/logs')) {
        mkdir(BASE_DIR . '/logs', 0755, true);
    }
} else {
    // Development: Show errors
    error_reporting(E_ALL);
    ini_set('display_errors', 1);
    ini_set('log_errors', 1);
}

// Billing/Payment Gateway Configuration
define('BILLING_GATEWAY', 'paymob'); // 'paymob', 'stripe', 'none'

// Paymob Configuration (Unified Checkout / Intention API)
// Get these from your Paymob dashboard: https://accept.paymob.com
if (!defined('PAYMOB_PUBLIC_KEY')) define('PAYMOB_PUBLIC_KEY', '');       // Public key for checkout iframe
if (!defined('PAYMOB_SECRET_KEY')) define('PAYMOB_SECRET_KEY', '');       // Secret key for API calls
if (!defined('PAYMOB_HMAC_SECRET')) define('PAYMOB_HMAC_SECRET', '');     // HMAC secret for callback verification
if (!defined('PAYMOB_INTEGRATION_IDS')) define('PAYMOB_INTEGRATION_IDS', '63364,65553,48519'); // Int'l 3DS, OmanNet 3DS, Apple Pay
if (!defined('PAYMOB_MOTO_INTEGRATION_ID')) define('PAYMOB_MOTO_INTEGRATION_ID', '63365');     // MOTO Int'l (card-on-file/subscriptions)
if (!defined('PAYMOB_MOTO_OMANNET_INTEGRATION_ID')) define('PAYMOB_MOTO_OMANNET_INTEGRATION_ID', '65554'); // MOTO OmanNet

// Legacy Amwal Pay Configuration (deprecated, kept for reference)
// if (!defined('AMWAL_MERCHANT_ID')) define('AMWAL_MERCHANT_ID', '');
// if (!defined('AMWAL_TERMINAL_ID')) define('AMWAL_TERMINAL_ID', '');
// if (!defined('AMWAL_SECURE_KEY')) define('AMWAL_SECURE_KEY', '');
// if (!defined('AMWAL_API_URL')) define('AMWAL_API_URL', 'https://backend.sa.amwal.tech');

// Stripe Configuration (alternative payment gateway)
if (!defined('STRIPE_SECRET_KEY')) define('STRIPE_SECRET_KEY', ''); // Stripe secret key
if (!defined('STRIPE_PUBLIC_KEY')) define('STRIPE_PUBLIC_KEY', ''); // Stripe public key

// LinkedIn OAuth Configuration (for social sharing and post automation)
if (!defined('LINKEDIN_CLIENT_ID')) define('LINKEDIN_CLIENT_ID', '');        // LinkedIn app client ID
if (!defined('LINKEDIN_CLIENT_SECRET')) define('LINKEDIN_CLIENT_SECRET', ''); // LinkedIn app client secret

// Anthropic Claude API (used by LinkedIn carousel slide generator)
// Accepts either a console API key (sk-ant-api03-...) or a Claude Code OAuth token (sk-ant-oat01-...)
if (!defined('ANTHROPIC_API_KEY')) define('ANTHROPIC_API_KEY', '');

// OpenRouter API key (primary AI translator for /api/translate.php, Qwen 3.6).
// If empty, translate.php falls back to OPENAI_API_KEY + gpt-4o-mini.
if (!defined('OPENROUTER_API_KEY')) define('OPENROUTER_API_KEY', '');
if (!defined('AI_MODEL')) define('AI_MODEL', 'qwen/qwen3.6-plus');

// Google Gemini API (used by LinkedIn carousel image generator)
if (!defined('GEMINI_API_KEY')) define('GEMINI_API_KEY', '');

// Print Webhook Configuration
// Global secret for verifying print status webhooks (per-shop secrets take priority)
// Callers must send X-Webhook-Signature: sha256=<hmac_hex_of_body>
if (!defined('PRINT_WEBHOOK_SECRET')) define('PRINT_WEBHOOK_SECRET', ''); // Set a random secret string

// SEO & Analytics
define('GA_MEASUREMENT_ID', '');         // Google Analytics e.g. G-XXXXXXXXXX
define('GOOGLE_SITE_VERIFICATION', '');  // Google Search Console verification meta tag content

// Email/SMTP Configuration (required for password reset, notifications)
// Common providers:
// - Gmail: smtp.gmail.com, port 587, tls (requires App Password)
// - Outlook: smtp.office365.com, port 587, tls
// - Mailgun: smtp.mailgun.org, port 587, tls
// - SendGrid: smtp.sendgrid.net, port 587, tls
if (!defined('MAIL_HOST')) define('MAIL_HOST', ''); // SMTP server hostname
if (!defined('MAIL_PORT')) define('MAIL_PORT', 587); // SMTP port (587 for TLS, 465 for SSL)
if (!defined('MAIL_USERNAME')) define('MAIL_USERNAME', ''); // SMTP username (usually email)
if (!defined('MAIL_PASSWORD')) define('MAIL_PASSWORD', ''); // SMTP password or app password
if (!defined('MAIL_ENCRYPTION')) define('MAIL_ENCRYPTION', 'tls'); // 'tls', 'ssl', or '' for none
if (!defined('MAIL_FROM_EMAIL')) define('MAIL_FROM_EMAIL', ''); // From email (defaults to username)
if (!defined('MAIL_FROM_NAME')) define('MAIL_FROM_NAME', 'Cardify'); // From name

// Apple Wallet Pass Configuration
// Requires: Apple Developer Program membership ($99/yr), Pass Type ID + cert,
// WWDR G4 intermediate cert. Full setup guide:
//   docs/superpowers/plans/2026-04-16-wallet-passes.md
//
// SECURITY: php-fpm here is open_basedir-jailed to /www/wwwroot/cardify.om/:/tmp/,
// so cert files MUST live under the webroot. Put them in data/wallet/ (0600,
// www:www) and keep the nginx "location ~ ^/data/wallet/ { return 404; }" +
// ".pem/.p12/.key" deny rules in the vhost, or the signing key is downloadable.
// .htaccess does NOTHING on this nginx stack.
if (!defined('APPLE_WALLET_ENABLED'))       define('APPLE_WALLET_ENABLED', false);
if (!defined('APPLE_WALLET_CERT_PATH'))     define('APPLE_WALLET_CERT_PATH', '');     // PEM w/ cert + private key (from .p12)
if (!defined('APPLE_WALLET_CERT_PASSWORD')) define('APPLE_WALLET_CERT_PASSWORD', ''); // password used when exporting the .p12
if (!defined('APPLE_WALLET_WWDR_PATH'))     define('APPLE_WALLET_WWDR_PATH', '');     // Apple WWDR G4 intermediate (PEM)
if (!defined('APPLE_WALLET_PASS_TYPE_ID'))  define('APPLE_WALLET_PASS_TYPE_ID', '');  // e.g. pass.om.cardify.businesscard
if (!defined('APPLE_WALLET_TEAM_ID'))       define('APPLE_WALLET_TEAM_ID', '');       // 10-char Apple Team ID
if (!defined('APPLE_WALLET_ORG_NAME'))      define('APPLE_WALLET_ORG_NAME', 'Cardify');

// Google Wallet Pass Configuration
// Requires: GCP project w/ Wallet API enabled, service account JSON, Issuer ID
// from pay.google.com/business/console. Full setup guide:
//   docs/superpowers/plans/2026-04-16-wallet-passes.md
if (!defined('GOOGLE_WALLET_ENABLED'))              define('GOOGLE_WALLET_ENABLED', false);
if (!defined('GOOGLE_WALLET_SERVICE_ACCOUNT_JSON')) define('GOOGLE_WALLET_SERVICE_ACCOUNT_JSON', ''); // path to service account key JSON
if (!defined('GOOGLE_WALLET_ISSUER_ID'))            define('GOOGLE_WALLET_ISSUER_ID', '');            // 10-16 digit issuer ID
if (!defined('GOOGLE_WALLET_CLASS_ID'))             define('GOOGLE_WALLET_CLASS_ID', 'cardify_business_card_v1'); // arbitrary class suffix

// Live Analytics (Convex sidecar)
// Hybrid event store, MySQL stays system of record. PHP additionally fires each
// card event to Convex over a 200ms-capped HTTP call so /admin/live-analytics.php
// can show reactive KPIs. Setup: docs/CONVEX_DEPLOY.md.
if (!defined('FEATURE_LIVE_ANALYTICS')) define('FEATURE_LIVE_ANALYTICS', false);
if (!defined('CONVEX_INGEST_URL'))      define('CONVEX_INGEST_URL', '');         // e.g. https://cardify.om/_convex/http/ingest
if (!defined('CONVEX_INGEST_SECRET'))   define('CONVEX_INGEST_SECRET', '');      // shared with Convex .env.convex
if (!defined('CONVEX_BROWSER_URL'))     define('CONVEX_BROWSER_URL', '');        // e.g. https://cardify.om/_convex/api
if (!defined('CONVEX_AUTH_SECRET'))     define('CONVEX_AUTH_SECRET', '');        // HS256 secret for admin JWT bridge

// Include required files
require_once INCLUDES_DIR . '/Database.php';
require_once INCLUDES_DIR . '/functions.php';
require_once INCLUDES_DIR . '/DatabaseAdapter.php';
require_once INCLUDES_DIR . '/AuditLog.php';

// Initialize database connection (if configured)
if (defined('DB_HOST') && !empty(DB_HOST) && !empty(DB_NAME)) {
    $db = Database::getInstance();
    if (!$db->isConnected()) {
        $db->connect(DB_HOST, DB_NAME, DB_USER, DB_PASS, DB_PORT, DB_TYPE);
    }
    // Initialize DatabaseAdapter
    DatabaseAdapter::init();
}

// Security headers (production), skip entirely on CLI (migrations/scripts)
if ($isProduction && php_sapi_name() !== 'cli') {
    // Force HTTPS in production (browser requests only)
    if (!isset($_SERVER['HTTPS']) && $_SERVER['HTTP_HOST'] !== 'localhost') {
        header('Location: https://' . $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI'], true, 301);
        exit;
    }
    
    // Security headers
    header('X-Content-Type-Options: nosniff');
    header('X-Frame-Options: SAMEORIGIN');
    header('X-XSS-Protection: 1; mode=block');
    header('Referrer-Policy: strict-origin-when-cross-origin');
    header('Permissions-Policy: camera=(), microphone=(), geolocation=()');

    // HSTS (HTTP Strict Transport Security) - only if HTTPS
    if (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on') {
        header('Strict-Transport-Security: max-age=31536000; includeSubDomains');
    }
}
