<?php
/**
 * Example configuration file.
 *
 * Copy to `config.php` and customize for your installation.
 * IMPORTANT: `config.php` is intentionally excluded from Git (contains secrets).
 * 
 * After installation, this file will be auto-generated by the installer.
 * You can also manually configure it using this template.
 */

// Start session
if (session_status() === PHP_SESSION_NONE) {
    session_start();
}

// Database configuration (set by installer)
define('DB_HOST', 'localhost');
define('DB_NAME', 'business_cards');
define('DB_USER', 'root');
define('DB_PASS', '');
define('DB_PORT', '3306');
define('DB_TYPE', 'mysql'); // 'mysql' or 'pgsql'

// Base paths
define('BASE_DIR', __DIR__);
define('INCLUDES_DIR', BASE_DIR . '/includes');
define('DATA_DIR', BASE_DIR . '/data');
define('UPLOADS_DIR', BASE_DIR . '/uploads');
define('TEMPLATES_DIR', UPLOADS_DIR . '/templates');
define('CARDS_DIR', UPLOADS_DIR . '/cards');
define('EXCEL_DIR', UPLOADS_DIR . '/excel');
define('ASSETS_DIR', BASE_DIR . '/assets');

// Data files (JSON fallback if database not available)
define('EMPLOYEES_JSON', DATA_DIR . '/employees.json');
define('TEMPLATES_JSON', DATA_DIR . '/templates.json');
define('GENERATED_JSON', DATA_DIR . '/generated.json');

// Site settings
define('SITE_NAME', 'Business Cards');
define('SITE_DESCRIPTION', 'Professional Business Card Generator');

// Timezone
date_default_timezone_set('Asia/Muscat');

// Error reporting (set to 0 in production)
error_reporting(E_ALL);
ini_set('display_errors', 1);

// Billing/Payment Gateway Configuration
define('BILLING_GATEWAY', 'amwal'); // 'amwal', 'stripe', 'none'
if (!defined('AMWAL_API_KEY')) define('AMWAL_API_KEY', ''); // Set your Amwal Pay API key
if (!defined('AMWAL_MERCHANT_ID')) define('AMWAL_MERCHANT_ID', ''); // Set your Amwal Pay merchant ID
if (!defined('AMWAL_API_URL')) define('AMWAL_API_URL', 'https://api.amwal.com/v1'); // Amwal Pay API URL
if (!defined('AMWAL_WEBHOOK_SECRET')) define('AMWAL_WEBHOOK_SECRET', ''); // Webhook secret for verification
if (!defined('STRIPE_SECRET_KEY')) define('STRIPE_SECRET_KEY', ''); // Stripe secret key
if (!defined('STRIPE_PUBLIC_KEY')) define('STRIPE_PUBLIC_KEY', ''); // Stripe public key

// Include required files
require_once INCLUDES_DIR . '/Database.php';
require_once INCLUDES_DIR . '/functions.php';
require_once INCLUDES_DIR . '/DatabaseAdapter.php';

// Initialize database connection (if configured)
if (defined('DB_HOST') && !empty(DB_HOST) && !empty(DB_NAME)) {
    $db = Database::getInstance();
    if (!$db->isConnected()) {
        $db->connect(DB_HOST, DB_NAME, DB_USER, DB_PASS, DB_PORT, DB_TYPE);
    }
    // Initialize DatabaseAdapter
    DatabaseAdapter::init();
}


