<?php
/** @var string $employeeName */
/** @var string $companyName */
/** @var string $editUrl */
/** @var int    $expiresInDays */
/** @var string|null $brandColor */
/** @var string|null $secondaryColor */
/** @var string|null $logoUrl */
/** @var string|null $supportEmail */
/** @var string|null $companyDomain */

$firstName  = htmlspecialchars(trim(strtok(trim($employeeName), ' ')) ?: 'there', ENT_QUOTES, 'UTF-8');
$companyEsc = htmlspecialchars($companyName, ENT_QUOTES, 'UTF-8');
$editUrlEsc = htmlspecialchars($editUrl, ENT_QUOTES, 'UTF-8');
$color      = $brandColor ?: '#2d13ea';
$colorEsc   = htmlspecialchars($color, ENT_QUOTES, 'UTF-8');
$supportEsc = htmlspecialchars($supportEmail ?: 'info@cardify.om', ENT_QUOTES, 'UTF-8');

// Logo as a small inline image at the top, falls back silently if missing.
$logoBlock = '';
if (!empty($logoUrl)) {
    $logoEsc = htmlspecialchars($logoUrl, ENT_QUOTES, 'UTF-8');
    $logoBlock = '<img src="' . $logoEsc . '" alt="' . $companyEsc . '" style="max-height:36px;display:block;margin:0 0 20px 0;">';
}

$subject = "{$companyName}, your digital business card";

// MINIMAL HTML body. M365 outbound spam classifier scores table-heavy
// templates and gradient inline styles aggressively. This version keeps
// tenant logo + one CTA button + brand-coloured link colour, and drops
// everything else. Sister plain-text part (auto-generated by Mailer)
// already carries the same content for non-HTML clients.
$body = <<<HTML
<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"></head>
<body style="font-family:-apple-system,Segoe UI,Roboto,Arial,sans-serif;line-height:1.6;color:#1f2937;max-width:560px;margin:0 auto;padding:24px;">
{$logoBlock}
<p>Hi {$firstName},</p>
<p>{$companyEsc} has set up a digital business card for you. Open your private link below to review the details on the card (name, position, phone, mobile, email) and update anything that needs changing.</p>
<p style="margin:24px 0;"><a href="{$editUrlEsc}" style="background:{$colorEsc};color:#ffffff;padding:12px 22px;border-radius:6px;text-decoration:none;display:inline-block;font-weight:600;">Review my card</a></p>
<p>Or open this link: <a href="{$editUrlEsc}" style="color:{$colorEsc};">{$editUrlEsc}</a></p>
<p>Changes save immediately and the printed and shared versions of your card update with them. You can reopen this link any time later if your role, phone, or email changes.</p>
<p style="color:#6b7280;font-size:13px;margin-top:32px;">{$companyEsc} team. Questions? Reply to this email or write to {$supportEsc}.</p>
</body>
</html>
HTML;
