<?php
/**
 * Cardify - Installer Layout Helpers
 * Lightweight header/footer for pre-config setup.
 */

function installerHeader($title, $basePath, $extraHead = '', $bodyClass = '') {
?>
<!DOCTYPE html>
<html lang="en" data-product="cardify" class="scroll-smooth">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?php echo htmlspecialchars($title); ?></title>
    <link rel="icon" href="<?php echo $basePath; ?>/favicon.svg" type="image/svg+xml">
    <link rel="alternate icon" href="<?php echo $basePath; ?>/favicon.ico">

    <link rel="preconnect" href="https://fonts.bhd.om">
    <link rel="preconnect" href="https://fonts.bhd.om" crossorigin>
    <link href="https://fonts.bhd.om/css2?family=Inter:wght@300;400;500;600;700;800&display=swap" rel="stylesheet">

    <!-- Font Awesome 7.2 Pro (design.bhd.om), ?v busts stale CF cache -->
    <link rel="stylesheet" href="https://design.bhd.om/fa/v7.2.0/css/fontawesome.min.css?v=7.2.0">
    <link rel="stylesheet" href="https://design.bhd.om/fa/v7.2.0/css/solid.min.css?v=7.2.0">
    <link rel="stylesheet" href="https://design.bhd.om/fa/v7.2.0/css/brands.min.css?v=7.2.0">

    <!-- Tailwind CSS (Local) -->
    <?php $tailwindVersion = @filemtime($_SERVER['DOCUMENT_ROOT'] . '/assets/techwind/css/tailwind.min.css') ?: time(); ?>
    <link rel="stylesheet" href="/assets/techwind/css/tailwind.min.css?v=<?php echo $tailwindVersion; ?>">
    
    <!-- Flowbite CSS (Local) -->
    <?php $flowbiteCssVersion = @filemtime($_SERVER['DOCUMENT_ROOT'] . '/assets/flowbite/app.css') ?: time(); ?>
    <link rel="stylesheet" href="/assets/flowbite/app.css?v=<?php echo $flowbiteCssVersion; ?>">
    <?php /* The utilities the site uses that neither Tailwind build contains.
       Both were generated on 16 Apr 2026 and never rebuilt, so classes added
       after that date rendered as nothing: text-start, rounded-3xl,
       scroll-mt-*, tabular-nums and 575 more. Generated by
       scripts/build-css-supplement.mjs; every rule in it is a class no other
       stylesheet defines, so nothing that renders today changes. */ ?>
    <?php $cardifySupplementVersion = @filemtime($_SERVER['DOCUMENT_ROOT'] . '/assets/css/cardify-tailwind-supplement.css') ?: time(); ?>
    <link rel="stylesheet" href="/assets/css/cardify-tailwind-supplement.css?v=<?php echo $cardifySupplementVersion; ?>">
    
    <link rel="stylesheet" href="<?php echo $basePath; ?>/assets/css/cardify-overrides.css">

    <style>
        body { font-family: 'Inter', ui-sans-serif, system-ui, sans-serif; }
        [x-cloak] { display: none !important; }
    </style>
    <?php if (!empty($extraHead)) echo $extraHead; ?>
    <?php /* Delegated behaviour, replacing the on* attributes. An inline
       handler is inline script, and a CSP without 'unsafe-inline' kills every
       one. Placed after the async stylesheets so its first pass already sees
       them. */ ?>
    <script src="/assets/js/cardify-actions.js?v=<?php echo @filemtime($_SERVER['DOCUMENT_ROOT'] . '/assets/js/cardify-actions.js') ?: time(); ?>"></script>
</head>
<body class="bg-gray-50 text-gray-900 antialiased <?php echo $bodyClass; ?>">
<?php
}

function installerFooter($extraScripts = '') {
?>
    <!-- Flowbite JS (Local) -->
    <?php $flowbiteJsVersion = @filemtime($_SERVER['DOCUMENT_ROOT'] . '/assets/flowbite/app.bundle.js') ?: time(); ?>
    <script src="/assets/flowbite/app.bundle.js?v=<?php echo $flowbiteJsVersion; ?>"></script>
    <?php if (!empty($extraScripts)) echo $extraScripts; ?>
</body>
</html>
<?php
}
