<?php
/**
 * The design system has to actually render.
 *
 * cardify.om ships two Tailwind builds, assets/techwind/css/tailwind.min.css
 * and assets/flowbite/app.css. Both were generated on 16 April 2026 and neither
 * was ever rebuilt, while pages kept adding classes. Every utility added after
 * that date rendered as nothing unless it happened to already be in one of
 * them. Measured on production during the 5 Sep 2026 gauntlet: text-start left
 * the /get-started hero centred at desktop, rounded-3xl left the demo card
 * square, scroll-mt-20 dropped anchor jumps under the sticky header,
 * tabular-nums did nothing on nine analytics tables, and 575 more.
 *
 * scripts/build-css-supplement.mjs emits the difference. This test fails when a
 * class the markup uses is styled by no stylesheet at all, so the next one
 * cannot go unnoticed for five months.
 */
$root = dirname(__DIR__, 2);
$failures = 0;
function twCheck(bool $c, string $label, string $detail = ''): void
{
    global $failures;
    echo ($c ? 'PASS  ' : 'FAIL  ') . $label;
    if (!$c && $detail !== '') echo ' (' . $detail . ')';
    echo "\n";
    if (!$c) $failures++;
}

$sheets = [
    'assets/techwind/css/tailwind.min.css',
    'assets/flowbite/app.css',
    'assets/vendor/flag-icons/css/flag-icons.min.css',
    'assets/css/cardify-tokens.css',
    'assets/css/cardify-components.css',
    'assets/css/cardify-overrides.css',
    'assets/css/cardify-brand-2026.css',
    'assets/css/cardify-hero-card.css',
    'assets/css/cardify-tailwind-supplement.css',
];
$missingFiles = array_values(array_filter($sheets, fn($f) => !is_file($root . '/' . $f)));
twCheck($missingFiles === [], 'every stylesheet in the list exists', implode(', ', $missingFiles));

twCheck(is_file($root . '/scripts/build-css-supplement.mjs'),
    'the generator is in the tree, so the supplement can be rebuilt');
foreach (['includes/ui-header.php', 'includes/admin-layout.php', 'includes/installer-layout.php'] as $layout) {
    twCheck(
        str_contains(file_get_contents($root . '/' . $layout), 'cardify-tailwind-supplement.css'),
        "{$layout} links the supplement"
    );
}

// The authority on "is this a Tailwind utility" is Tailwind. Regenerating the
// supplement and comparing is the only check that cannot be fooled by a
// bespoke component class defined in a page's own inline <style> block.
$node = trim((string) @shell_exec('command -v node 2>/dev/null'));
if ($node === '' || !is_dir($root . '/node_modules/tailwindcss')) {
    echo "SKIP  node or tailwindcss missing, cannot regenerate the supplement\n";
} else {
    $out = [];
    $code = 0;
    exec('cd ' . escapeshellarg($root) . ' && ' . escapeshellarg($node)
        . ' scripts/build-css-supplement.mjs --check 2>&1', $out, $code);
    twCheck(
        $code === 0,
        'the supplement is current, so no class in the markup is styled nowhere',
        implode(' ', array_slice($out, -3))
    );
}

// Cheap guards that run everywhere, including where node is absent.
$supplement = file_get_contents($root . '/assets/css/cardify-tailwind-supplement.css');
twCheck(str_contains($supplement, 'Generated by scripts/build-css-supplement.mjs'),
    'the supplement says what generated it');
foreach (['text-start', 'rounded-3xl', 'scroll-mt-20', 'tabular-nums'] as $cls) {
    $needle = '.' . preg_replace('/([^A-Za-z0-9_-])/', '\\\\$1', $cls) . '{';
    twCheck(str_contains($supplement, $needle), "the supplement styles {$cls}, which rendered as nothing on production");
}

// A rule that some other stylesheet already defines must NOT be here: the
// supplement is additive on purpose, so nothing that renders today changes.
$shippedCss = '';
foreach ($sheets as $rel) {
    if (str_contains($rel, 'supplement')) continue;
    $shippedCss .= (string) @file_get_contents($root . '/' . $rel);
}
$shippedNames = [];
if (preg_match_all('/\.((?:[A-Za-z0-9_-]|\\\\.)+)/', $shippedCss, $m)) {
    foreach ($m[1] as $n) $shippedNames[str_replace('\\', '', $n)] = true;
}
$overlap = [];
if (preg_match_all('/\.((?:[A-Za-z0-9_-]|\\\\.)+)\s*\{/', $supplement, $m2)) {
    foreach (array_unique($m2[1]) as $n) {
        $plain = str_replace('\\', '', $n);
        if (isset($shippedNames[$plain])) $overlap[] = $plain;
    }
}
twCheck($overlap === [], 'the supplement re-declares nothing another stylesheet already styles',
    implode(', ', array_slice($overlap, 0, 8)));

$emDash = "\xE2\x80\x94";
twCheck(!str_contains(file_get_contents($root . '/scripts/build-css-supplement.mjs'), $emDash),
    'scripts/build-css-supplement.mjs contains no em dash');

echo $failures === 0 ? "\nALL PASS\n" : "\n{$failures} FAILED\n";
exit($failures === 0 ? 0 : 1);
