<?php
/**
 * Create the MHD ITICS-family per-division card templates from the clean bg +
 * corrected per-division fields_json (generated by docs/mhd/build_templates.py,
 * staged at /tmp/mhd-clean/). Clones the working template row structure, swaps
 * bg + fonts to the shared clean import dir, links each department to its pair.
 *
 * Run: /www/server/php/83/bin/php scripts/mhd/build-division-templates.php
 */
require_once __DIR__ . '/../../config.php';
$db  = Database::getInstance();
$CID = 'a9ba4c5e-7b8e-4ccc-a3bd-08ab9af7b1d5';
$IMPORT = '/uploads/templates/imports/mhd-clean-v1';
$stage  = '/tmp/mhd-clean';

$manifest = json_decode(file_get_contents("$stage/div-manifest.json"), true);
$refFront = $db->fetchOne("SELECT * FROM templates WHERE id='723b11ee-5a40-4cf0-b99e-73b1ea35b6ea'");
$refBack  = $db->fetchOne("SELECT * FROM templates WHERE id='479dc3cb-8eef-4f71-8ea7-3dc98dbb32a5'");
if (!$refFront || !$refBack) { fwrite(STDERR, "reference templates missing\n"); exit(1); }

$drop = ['created_at','updated_at','deleted_at'];
foreach ($manifest as $m) {
    $slug = $m['slug'];
    $pairId = generateUUID();
    foreach (['front' => $refFront, 'back' => $refBack] as $side => $ref) {
        $fj = file_get_contents("$stage/div-$slug-$side.json");
        if ($fj === false) { fwrite(STDERR, "missing fields for $slug $side\n"); exit(1); }
        $row = $ref;
        foreach ($drop as $c) unset($row[$c]);
        $row['id']                    = generateUUID();
        $row['company_id']            = $CID;
        $row['pair_id']               = $pairId;
        $row['side']                  = $side;
        $row['name']                  = 'MHD ' . ucwords(str_replace('-', ' ', $slug));
        $row['fields_json']           = $fj;
        $row['background_image_path'] = "$IMPORT/bg-page-" . ($side === 'front' ? 1 : 2) . ".png";
        $row['fonts_dir']             = "$IMPORT/fonts";
        $row['has_vector_source']     = 1;
        $row['current_version']       = 1;
        $db->insert('templates', $row);
        echo "created $slug $side {$row['id']}\n";
    }
    $db->update('departments', ['template_pair_id' => $pairId],
        'company_id = :c AND slug = :s', ['c' => $CID, 's' => $slug]);
    echo "linked dept $slug -> pair $pairId\n";
}
echo "done: " . count($manifest) . " divisions\n";
